### PR TITLE
French compendium and other modifications

### PR DESCRIPTION
**Pull request by Lanneval**
Upload french compendium.

And modification in te system for that, i have forget to suppr c&c p 99, sorry.

### CODE REVIEW

**Comment by Xzotl42** [comment]
I noticed afterward the wrong place of the files and fixed it on my side. It was very confusing at first as my IDE was returning one file or the other. :)
Please be patient if I don't merge your pull request right away, I have a big commit coming with the magic items implementation and I will deal with any conflict afterward

**Comment by Xzotl42** [comment]
Concerning the french compendium (or any other language), I think it may be better to have them in a separate module.
We need to agree on a structure (how many compendiums, containing what) and some naming convention common to all languages. (arm5e-fr for example).

Since you did complete the translation in french, you may have noticed I started to add a mnemonic for the name of a compendium ("arm5e.packs.abilities.name"). Those will be used to lookup in the proper compendium and the right module if available to retrieve the translated version of an ability, spell, virtue, etc.

There was a discussion about it on the discord server, if you want to make adjustments to the proposal I made

**Comment by Lanneval** [comment]
Hello,

I am agree with you. Now i must learn how to make a module.

Arnaud

**Review by Xzotl42 — CHANGES_REQUESTED** [review]
As discussed previously, could  you remove the french compendiums from the pull request? I will try to post a guide on how to create a module with compendiums for a specific language on discord

**Pull request closed without merging**
